// ملف بيانات المنتجات - مع مسارات الصور المحلية (images/كود-الجهاز.jpg)
const products = [
    // ===== WIFI SMART US SWITCHES =====
    { id: 1, name: "WS-TG-US-T", description: "WiFi Smart Toggle Style Switch US Neutral Wire Required 3-Way Switch. Input Power: 100~245V AC 50/60Hz, Wireless Protocol: WiFi 802.11 b/g/n 2.4GHz, Max Current: 10A, Color: White", price: 1750, category: "wifi-switches", image: "images/WS-TG-US-T.jpg" },
    { id: 2, name: "WS-SR-US-T", description: "MOES Star Ring 2nd Generation Smart Single Pole 3 Way WIFI Switch 1 Gang US Standard. Input Power: 100~245V AC 50/60Hz, Max Current: 10A, Color: White, Dimension: 106*45*35 mm", price: 1060, category: "wifi-switches", image: "images/WS-SR-US-T.jpg" },
    { id: 3, name: "MWS-B-US1", description: "Moes WiFi Smart Light Button Switch 1 Gang Neutral Wire Required US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 1230, category: "wifi-switches", image: "images/MWS-B-US1.jpg" },
    { id: 4, name: "MWS-B-US2", description: "Moes WiFi Smart Light Button Switch 2 Gang Neutral Wire Required US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 1320, category: "wifi-switches", image: "images/MWS-B-US2.jpg" },
    { id: 5, name: "MWS-B-US3", description: "Moes WiFi Smart Light Button Switch 3 Gang Neutral Wire Required US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 1420, category: "wifi-switches", image: "images/MWS-B-US3.jpg" },
    { id: 6, name: "MWS-B-US4", description: "Moes WiFi Smart Light Button Switch 4 Gang Neutral Wire Required US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 1510, category: "wifi-switches", image: "images/MWS-B-US4.jpg" },
    { id: 7, name: "MWS-US1", description: "Moes Matter Smart Light Switch 1 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1250, category: "wifi-switches", image: "images/MWS-US1.jpg" },
    { id: 8, name: "MWS-US2", description: "Moes Matter Smart Light Switch 2 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1340, category: "wifi-switches", image: "images/MWS-US2.jpg" },
    { id: 9, name: "MWS-US3", description: "Moes Matter Smart Light Switch 3 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1360, category: "wifi-switches", image: "images/MWS-US3.jpg" },
    { id: 10, name: "MWS-US4", description: "Moes Matter Smart Light Switch 4 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1510, category: "wifi-switches", image: "images/MWS-US4.jpg" },
    { id: 11, name: "WRS-US1", description: "Moes WiFi Smart Light Switch 1 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1250, category: "wifi-switches", image: "images/WRS-US1.jpg" },
    { id: 12, name: "WRS-US2", description: "Moes WiFi Smart Light Switch 2 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1320, category: "wifi-switches", image: "images/WRS-US2.jpg" },
    { id: 13, name: "WRS-US3", description: "Moes WiFi Smart Light Switch 3 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1360, category: "wifi-switches", image: "images/WRS-US3.jpg" },
    { id: 14, name: "WRS-US4", description: "Moes WiFi Smart Light Switch 4 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1490, category: "wifi-switches", image: "images/WRS-US4.jpg" },
    { id: 15, name: "MWS-DL-US1", description: "Matter WiFi Smart Light Switch 1 Gang Concave Glass Panel Neutral Wire Required US Version. Voltage: 90V-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1280, category: "wifi-switches", image: "images/MWS-DL-US1.jpg" },
    { id: 16, name: "MWS-DL-US2", description: "Matter WiFi Smart Light Switch 2 Gang Concave Glass Panel Neutral Wire Required US Version. Voltage: 90V-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1380, category: "wifi-switches", image: "images/MWS-DL-US2.jpg" },
    { id: 17, name: "MWS-DL-US3", description: "Matter WiFi Smart Light Switch 3 Gang Concave Glass Panel Neutral Wire Required US Version. Voltage: 90V-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1480, category: "wifi-switches", image: "images/MWS-DL-US3.jpg" },
    { id: 18, name: "MWS-DL-US4", description: "Matter WiFi Smart Light Switch 4 Gang Concave Glass Panel Neutral Wire Required US Version. Voltage: 90V-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1580, category: "wifi-switches", image: "images/MWS-DL-US4.jpg" },
    { id: 19, name: "WS-SF-US1", description: "WiFi Star Feather Series All Touch Smart Switch 1 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 1830, category: "wifi-switches", image: "images/WS-SF-US1.jpg" },
    { id: 20, name: "WS-SF-US2", description: "WiFi Star Feather Series All Touch Smart Switch 2 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 1940, category: "wifi-switches", image: "images/WS-SF-US2.jpg" },
    { id: 21, name: "WS-SF-US3", description: "WiFi Star Feather Series All Touch Smart Switch 3 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 2040, category: "wifi-switches", image: "images/WS-SF-US3.jpg" },
    { id: 22, name: "WS-SF-US4", description: "WiFi Star Feather Series All Touch Smart Switch 4 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 2150, category: "wifi-switches", image: "images/WS-SF-US4.jpg" },
    { id: 23, name: "WS-SR-USD-T", description: "MOES Star Ring WiFi Smart Dimmer Light Switch 3Way Grounding Design App Control US Standard. Input voltage: 90-250V AC, 50/60Hz, Output voltage: 90-250V AC, 50/60Hz, Maximum output current: 175W LED/CFL, 350W incandescent, Color: White", price: 1810, category: "wifi-switches", image: "images/WS-SR-USD-T.jpg" },
    { id: 24, name: "WS-USD1", description: "MOES WiFi Dimmer Switch Smart Light Dimmer Touch Panel Switches 1 Gang US Version. Working Voltage: 90-250V AC 50/60Hz, Max. Load: 600W(INC)/220V; 150W(LED/CFL)/220V; Color: White / Black", price: 1450, category: "wifi-switches", image: "images/WS-USD1.jpg" },
    { id: 25, name: "WS-USD2", description: "MOES WiFi Dimmer Switch Smart Light Dimmer Touch Panel Switches 2 Gang US Version. Working Voltage: 90-250V AC 50/60Hz, Max. Load: 600W(INC)/220V; 150W(LED/CFL)/220V; Color: White / Black", price: 1640, category: "wifi-switches", image: "images/WS-USD2.jpg" },
    { id: 26, name: "WS-USD3", description: "MOES WiFi Dimmer Switch Smart Light Dimmer Touch Panel Switches 3 Gang US Version. Working Voltage: 90-250V AC 50/60Hz, Max. Load: 600W(INC)/220V; 150W(LED/CFL)/220V; Color: White / Black", price: 1810, category: "wifi-switches", image: "images/WS-USD3.jpg" },

    // ===== ZIGBEE SMART US SWITCHES =====
    { id: 27, name: "ZS-SR-US-T", description: "MOES Star Ring 2nd Generation Smart Single Pole 3 Way Zigbee Switch 1 Gang US Standard. Input Power: 100~245V AC 50/60Hz, Max Current: 10A, Color: White, Dimension: 106*45*35 mm", price: 1270, category: "zigbee-switches", image: "images/ZS-SR-US-T.jpg" },
    { id: 28, name: "ZS-B-US1", description: "Moes Zigbee Smart Light Button Switch 1 Gang Neutral Wire Optional US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 1630, category: "zigbee-switches", image: "images/ZS-B-US1.jpg" },
    { id: 29, name: "ZS-B-US2", description: "Moes Zigbee Smart Light Button Switch 2 Gang Neutral Wire Optional US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 1740, category: "zigbee-switches", image: "images/ZS-B-US2.jpg" },
    { id: 30, name: "ZS-B-US3", description: "Moes Zigbee Smart Light Button Switch 3 Gang Neutral Wire Optional US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 1850, category: "zigbee-switches", image: "images/ZS-B-US3.jpg" },
    { id: 31, name: "ZS-B-US4", description: "Moes Zigbee Smart Light Button Switch 4 Gang Neutral Wire Optional US Standard. Voltage: 90-240V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White", price: 2140, category: "zigbee-switches", image: "images/ZS-B-US4.jpg" },
    { id: 32, name: "ZS-US1-LN", description: "Moes Zigbee Smart Light Switch 1 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1270, category: "zigbee-switches", image: "images/ZS-US1-LN.jpg" },
    { id: 33, name: "ZS-US2-LN", description: "Moes Zigbee Smart Light Switch 2 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1340, category: "zigbee-switches", image: "images/ZS-US2-LN.jpg" },
    { id: 34, name: "ZS-US3-LN", description: "Moes Zigbee Smart Light Switch 3 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1380, category: "zigbee-switches", image: "images/ZS-US3-LN.jpg" },
    { id: 35, name: "ZS-US4-LN", description: "Moes Zigbee Smart Light Switch 4 Gang Glass Panel Neutral Wire Required US Standard. Voltage: 90-250V AC, 50/60Hz, Max. Current: 10A/Gang; Total 10A, Color: White / Black", price: 1520, category: "zigbee-switches", image: "images/ZS-US4-LN.jpg" },
    { id: 36, name: "ZS-SF-US1", description: "Zigbee Star Feather Series All Touch Smart Switch 1 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 1960, category: "zigbee-switches", image: "images/ZS-SF-US1.jpg" },
    { id: 37, name: "ZS-SF-US2", description: "Zigbee Star Feather Series All Touch Smart Switch 2 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 2080, category: "zigbee-switches", image: "images/ZS-SF-US2.jpg" },
    { id: 38, name: "ZS-SF-US3", description: "Zigbee Star Feather Series All Touch Smart Switch 3 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 2170, category: "zigbee-switches", image: "images/ZS-SF-US3.jpg" },
    { id: 39, name: "ZS-SF-US4", description: "Zigbee Star Feather Series All Touch Smart Switch 4 Gang With Neutral. Voltage: 90-250V AC, 50/60Hz, Max.Current: 10A/Gang; Total 10A, Color: White / Grey", price: 2290, category: "zigbee-switches", image: "images/ZS-SF-US4.jpg" },
    { id: 40, name: "ZS-USD1", description: "MOES Zigbee Dimmer Switch Smart Light Dimmer Touch Panel Switches 1 Gang US Version. Working Voltage: 90-250V AC 50/60Hz, Max. Load: 600W(INC)/220V; 150W(LED/CFL)/220V; Color: White / Black", price: 1920, category: "zigbee-switches", image: "images/ZS-USD1.jpg" },
    { id: 41, name: "ZS-USD2", description: "MOES Zigbee Dimmer Switch Smart Light Dimmer Touch Panel Switches 2 Gang US Version. Working Voltage: 90-250V AC 50/60Hz, Max. Load: 600W(INC)/220V; 150W(LED/CFL)/220V; Color: White / Black", price: 2030, category: "zigbee-switches", image: "images/ZS-USD2.jpg" },
    { id: 42, name: "ZS-USD3", description: "MOES Zigbee Dimmer Switch Smart Light Dimmer Touch Panel Switches 3 Gang US Version. Working Voltage: 90-250V AC 50/60Hz, Max. Load: 600W(INC)/220V; 150W(LED/CFL)/220V; Color: White / Black", price: 2160, category: "zigbee-switches", image: "images/ZS-USD3.jpg" },

    // ===== WIFI SMART MINI SWITCHES =====
    { id: 43, name: "MWM-104-M", description: "WiFi Matter Mini Smart Switch Module Relay. Voltage: 90-250V AC 50/60Hz; 5-30V DC, Current: 10A/Gang; Total 10A, Operation Temp.: -10ºC ~ 65ºC, Dims (WxDxH): 40x40x18 mm, IP Rating: IP20", price: 1110, category: "wifi-mini", image: "images/MWM-104-M.jpg" },
    { id: 44, name: "WM-104-M-16AM", description: "WiFi Mini Smart Switch Module Relay With Energy Monitor. Voltage: 90-250V AC 50/60Hz; 5-30V DC, Current: 16A/Gang; Total 16A, Operation Temp.: -10ºC ~ 65ºC, Dims (WxDxH): 40x40x18 mm, IP Rating: IP20", price: 1380, category: "wifi-mini", image: "images/WM-104-M- 16AM.jpg" },
    { id: 45, name: "WM-104-M-LT", description: "WiFi Mini DIY Smart Light Switch Module Relay 1 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 10A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 690, category: "wifi-mini", image: "images/WM-104-M-LT.jpg" },
    { id: 46, name: "WM-104B-M-LT", description: "WiFi Mini DIY Smart Light Switch Module Relay 2 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 10A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 890, category: "wifi-mini", image: "images/WM-104B-M-LT.jpg" },
    { id: 47, name: "WM-104C-M-LT", description: "WiFi Mini DIY Smart Light Switch Module Relay 3 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 5A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 1080, category: "wifi-mini", image: "images/WM-104C-M-LT.jpg" },
    { id: 48, name: "WM-104D-M-LT", description: "WiFi Mini DIY Smart Light Switch Module Relay 4 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 5A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 1320, category: "wifi-mini", image: "images/WM-104D-M-LT.jpg" },
    { id: 49, name: "WM-105-M", description: "WiFi Smart Dimmer Switch Module Timer Diy Breaker 1 Gang. Voltage: 90-250VAC, Max power: 75W 110V/150W 220V, Operation temp: 0℃-40℃, Dims(WxDxH): 40x40x18mm, IP rating: IP20", price: 1190, category: "wifi-mini", image: "images/WM-105-M.jpg" },
    { id: 50, name: "WM-105B-M", description: "WiFi Smart Dimmer Switch Module Timer Diy Breaker 2 Gang. Voltage: 90-250VAC, Max power: 75W 110V/150W 220V, Operation temp: 0℃-40℃, Dims(WxDxH): 40x40x18mm, IP rating: IP20", price: 1430, category: "wifi-mini", image: "images/WM-105B-M.jpg" },

    // ===== ZIGBEE SMART MINI SWITCHES =====
    { id: 51, name: "ZM-104-M-16AM", description: "Zigbee Mini Smart Switch Module Relay With Energy Monitor. Voltage: 90-250V AC 50/60Hz; 5-30V DC, Current: 16A/Gang; Total 16A, Operation Temp.: -10ºC ~ 65ºC, Dims (WxDxH): 40x40x18 mm, IP Rating: IP20", price: 1440, category: "zigbee-mini", image: "images/ZM-104-M-16AM.jpg" },
    { id: 52, name: "ZM-104-M-LT", description: "Zigbee Mini DIY Smart Light Switch Module Relay 1 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 10A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 950, category: "zigbee-mini", image: "images/ZM-104-M-LT.jpg" },
    { id: 53, name: "ZM-104B-M-LT", description: "Zigbee Mini DIY Smart Light Switch Module Relay 2 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 10A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 1130, category: "zigbee-mini", image: "images/ZM-104B-M-LT.jpg" },
    { id: 54, name: "ZM-104C-M-LT", description: "Zigbee Mini DIY Smart Light Switch Module Relay 3 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 5A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 1320, category: "zigbee-mini", image: "images/ZM-104C-M-LT.jpg" },
    { id: 55, name: "ZM-104D-M-LT", description: "Zigbee Mini DIY Smart Light Switch Module Relay 4 Gang. Voltage: 90-250V AC50/60Hz, Current: Total 5A, Operation Temp: -10℃~65℃, Dims (WxDxH): 40x40x18mm, IP Rating: IP20", price: 1530, category: "zigbee-mini", image: "images/ZM-104D-M-LT.jpg" },
    { id: 56, name: "ZM-105-M", description: "Zigbee Smart Dimmer Switch Module Timer Diy Breaker 1 Gang. Voltage: 90-250VAC, Max power: 75W 110V/150W 220V, Operation temp: 0℃-40℃, Dims(WxDxH): 40x40x18mm, IP rating: IP20", price: 1400, category: "zigbee-mini", image: "images/ZM-105-M.jpg" },
    { id: 57, name: "ZM-105B-M", description: "Zigbee Smart Dimmer Switch Module Timer Diy Breaker 2 Gang. Voltage: 90-250VAC, Max power: 75W 110V/150W 220V, Operation temp: 0℃-40℃, Dims(WxDxH): 40x40x18mm, IP rating: IP20", price: 1600, category: "zigbee-mini", image: "images/ZM-105B-M.jpg" },

    // ===== STAIRCASE LIGHTING CONTROLLER =====
    { id: 58, name: "Stair Controller", description: "32-channel stair sensor. Input Voltage : 12-24V (DC), Channel : 32 (set to 1-32 step), Sensors : 2 Pir Sensor", price: 3600, category: "staircase", image: "images/Stair Controller.jpg" },
    { id: 59, name: "Power supply", description: "12V Power Supply 30A 240W AC DC Adapter, 110V / 220V AC to DC 12 Volt 30 Amp.", price: 650, category: "staircase", image: "images/Power supply.jpg" },

    // ===== RGB LIGHTING CONTROL PRODUCTS =====
    { id: 60, name: "WLS-CL-TV", description: "MOES Smart WiFi Ambient Lighting 65\" TV Backlight 4K HDMI 2.0 Sync Box LED Light Strip Music. The light color changes with the display color of the screen in real time, dynamic updating give you better experience in the whole viewing.", price: 6070, category: "rgb", image: "images/WLS-CL-TV.jpg" },
    { id: 61, name: "WLS-N01-RIC-3", description: "WIFI+BLE Neon Music 3 Meter LED Smart Light with Remote Control 16 Million Colors. Voltage: DC5V, Current: 1500mA, Power: 8W, IP rating: IP67, Light guide direction: Backlit or side light, Dimension: 3m*8mm*17mm, LED QTY: RGB 5050 72LEDS/m", price: 2740, category: "rgb", image: "images/WLS-N01-RIC-3.jpg" },

    // ===== WIFI SMART SOCKETS =====
    { id: 62, name: "Wi-Fi Smart Socket", description: "Smart Socket WiFi works with Amazon Alexa and Google home to manage your home devices through voice control. Max Current : 10A, Color : Black / White", price: 3530, category: "wifi-sockets", image: "images/Wi-Fi Smart Socket.jpg" },
    { id: 63, name: "WK-Y-EU-1U1C", description: "WiFi EU Smart Socket. 90-250V AC 50/60HZ 16A, Fast charger USB +Type C, Color : White", price: 2530, category: "wifi-sockets", image: "images/WK-Y-EU-1U1C.jpg" },
    { id: 64, name: "WK-Y-UN", description: "WiFi EU/UK/UN Smart Socket. 90-250V AC 50/60HZ 16A, Color : White / Black", price: 2010, category: "wifi-sockets", image: "images/WK-Y-UN.jpg" },
    { id: 65, name: "WS-Y-EU2P", description: "Two Panels", price: 130, category: "wifi-sockets", image: "images/WS-Y-EU2P.jpg" },
    { id: 66, name: "WS-Y-EU3P", description: "Three Panels", price: 170, category: "wifi-sockets", image: "images/WS-Y-EU3Pb.jpg" },
    { id: 67, name: "MWP-EU16M", description: "Matter Wifi EU Socket with power monitor. 95-250V AC 50/60HZ 16A", price: 1230, category: "wifi-sockets", image: "images/MWP-EU16M.jpg" },

    // ===== ZIGBEE POWER CONTROL PRODUCTS =====
    { id: 68, name: "Zigbee Smart Socket", description: "Smart Socket Zigbee works with Amazon Alexa and Google home to manage your home devices through voice control. Max Current : 10A, Color : Black / White", price: 3660, category: "zigbee-sockets", image: "images/Zigbee Smart Socket.jpg" },
    { id: 69, name: "ZK-SR-UK", description: "Zigbee UK Smart Socket. 100-240V AC 50/60HZ,86*86mm，16A, Color : White / Grey", price: 2270, category: "zigbee-sockets", image: "images/ZK-SR-UK.jpg" },
    { id: 70, name: "ZK-SR-EU", description: "Zigbee EU Smart Socket. 100-240V AC 50/60HZ,86*86mm，16A, Color : White / Grey", price: 2270, category: "zigbee-sockets", image: "images/ZK-SR-EU.jpg" },
    { id: 71, name: "TK-SR-EU-2C1A-30", description: "Fast Charging Wall Outlet USB + Type C. Max Power:30W, Color : White / Grey", price: 1770, category: "zigbee-sockets", image: "images/TK-SR-EU-2C1A-30.jpg" },
    { id: 72, name: "PP-SR-EU2P", description: "Two Panels", price: 220, category: "zigbee-sockets", image: "images/PP-SR-EU2P.jpg" },
    { id: 73, name: "PP-SR-EU3P", description: "Three Panels", price: 290, category: "zigbee-sockets", image: "images/PP-SR-EU3P.jpg" },
    { id: 74, name: "PP-SR-EU4P", description: "Four Panels", price: 370, category: "zigbee-sockets", image: "images/PP-SR-EU4P.jpg" },

    // ===== WIFI SHUTTER AND CURTAIN CONTROL PRODUCTS =====
    { id: 75, name: "WRS-USC", description: "WiFi Curtain Blinds Roller Shutter Switch RF433 Smart Touch Curtain Switch Single Pole Neutral Wire Required US. Maximum Power:≤1000W, Color : White / Black", price: 1600, category: "wifi-curtain", image: "images/WRS-USC.jpg" },
    { id: 76, name: "WRS-USC2", description: "WiFi RF433 Smart Curtain 2 Gang Blind Touch Switch Single Pole Neutral Wire Required US. Load Power≤600W Per Motor, Current:2.5A Per Motor, Color : White / Black", price: 2380, category: "wifi-curtain", image: "images/WRS-USC2.jpg" },
    { id: 77, name: "WM-108-M", description: "WiFi Smart Curtain Switch Module Mini Switch. Voltage: 90-250V AC 50/60Hz, Current: 2.5A/Gang;Total 2.5A, Dims (WxDxH): 40x40x18 mm, IP Rating: IP20", price: 1030, category: "wifi-curtain", image: "images/WM-108-M.jpg" },
    { id: 78, name: "MS-108WR", description: "Wi-Fi RF433 Smart Curtain Switch Module for Electric Motorized Roller Blinds Shutter Motor. Max. Current(pure resistive load): 2A, Max. Load Power: 500W", price: 1460, category: "wifi-curtain", image: "images/MS-108WR.jpg" },

    // ===== ZIGBEE SHUTTER AND CURTAIN CONTROL PRODUCTS =====
    { id: 79, name: "ZRS-USC", description: "Zigbee Curtain Blinds Roller Shutter Switch RF433 Smart Touch Curtain Switch Single Pole Neutral Wire Required US. Maximum Power:≤1000W, Color : White / Black", price: 1950, category: "zigbee-curtain", image: "images/ZRS-USC.jpg" },
    { id: 80, name: "ZM-108-M", description: "Zigbee Smart Curtain Switch Module Mini Switch. Voltage: 90-250V AC 50/60Hz, Current: 2.5A/Gang;Total 2.5A, Dims (WxDxH): 40x40x18 mm, IP Rating: IP20", price: 1220, category: "zigbee-curtain", image: "images/ZM-108-M.jpg" },
    { id: 81, name: "MS-108ZR", description: "Zigbee RF433 Smart Curtain Switch Module for Electric Motorized Roller Blinds Shutter Motor. Max. Current(pure resistive load): 2A, Max. Load Power: 500W", price: 1940, category: "zigbee-curtain", image: "images/MS-108ZR.jpg" },

    // ===== CURTAIN CONTROL ACCESSORIES =====
    { id: 82, name: "Curtain motor", description: "Smart Curtain motor to Control in curtain by touchable, remote control and mobile application Suitable for a curtain of 50 kilograms", price: 6620, category: "curtain-accessories", image: "images/Curtain motor.jpg" },
    { id: 83, name: "Curtain track", description: "Smart holder for curtain per meter", price: 1430, category: "curtain-accessories", image: "images/Curtain track.jpg" },
    { id: 84, name: "Curved Curtain track", description: "Curved Smart holder for curtain per meter", price: 2860, category: "curtain-accessories", image: "images/Curved Curtain track.jpg" },
    { id: 85, name: "Remote Control", description: "Dooya Remote Control DC2700AC For Electric Curtain Motor", price: 400, category: "curtain-accessories", image: "images/Remote Control.jpg" },

    // ===== NOT SMART MOTION SENSORS =====
    { id: 86, name: "motion sensor", description: "360 Degree PIR spot Motion Sensor - 1200w White Recessed Ceiling Mounted Occupancy Light Switch with Adjustable Timer & LUX Control", price: 540, category: "motion-sensors", image: "images/motion sensor.jpg" },
    { id: 87, name: "motion sensor", description: "Latch Motion Sensor. 220VAC, 1200 Watt, 360 Degree PIR Motion Sensor Light Switch Ceiling Mounted With Adjustable LUX, Sensitivity & Time, Detection Range: 6m Max; Installation Height: 2-4.5m Diameter 114mm, depth 57mm", price: 540, category: "motion-sensors", image: "images/motion sensor.jpg" },

    // ===== WIFI SMART MOTION & PRESENCE SENSOR =====
    { id: 88, name: "WSS-HP03-WH-U", description: "Wi-Fi human presence sensor + Light Sensor USB 5V 1A", price: 2160, category: "wifi-sensors", image: "images/WSS-HP03-WH-U.jpg" },
    { id: 89, name: "WSS-QY-HP", description: "WiFi human presence sensor + Light Sensor", price: 2790, category: "wifi-sensors", image: "images/WSS-QY-HP.jpg" },
    { id: 90, name: "WSS-FL-PIR-A", description: "WiFi Infrared human sensor 2*AA battery", price: 1800, category: "wifi-sensors", image: "images/WSS-FL-PIR-A.jpg" },

    // ===== ZIGBEE SMART MOTION & PRESENCE SENSOR =====
    { id: 91, name: "ZSS-QY-HP", description: "Zigbee human presence sensor + Light Sensor", price: 3240, category: "zigbee-sensors", image: "images/ZSS-QY-HP.jpg" },
    { id: 92, name: "ZSS-LP-HP02", description: "Zigbee human presence sensor + Light Sensor", price: 3240, category: "zigbee-sensors", image: "images/ZSS-LP-HP02.jpg" },
    { id: 93, name: "ZSS-HP05-A", description: "Zigbee human presence sensor + PIR Sensor 2*AAA exclude", price: 2180, category: "zigbee-sensors", image: "images/ZSS-HP05-A.jpg" },
    { id: 94, name: "ZSS-S01-PIR", description: "Zigbee Infrared human sensor 1*CR2450 Battery Include", price: 1430, category: "zigbee-sensors", image: "images/ZSS-S01-PIR.jpg" },

    // ===== UNIVERSAL REMOTE CONTROLS =====
    { id: 95, name: "WR-FL-IRF-U", description: "MOES WiFi USB Smart IR+RF Wireless Universal Remote Controller. Infrared Range: ≤ 12 Meters, Radio Frequency: 433/315MHz", price: 1610, category: "remotes", image: "images/WR-FL-IRF-U.jpg" },
    { id: 96, name: "WR-FL-IR-U", description: "MOES WiFi USB Smart IR Wireless Universal Remote Controller. Infrared Range: ≤ 12 Meters", price: 1110, category: "remotes", image: "images/WR-FL-IR-U.jpg" },
    { id: 97, name: "UFO-R11", description: "Tuya ZigBee Smart IR Remote Control Universal Infrared Remote Controller for AC TV DVD. Power Input: AAA battery ×2, Controlling Distance: ≤8m(Finally effect by environment)", price: 1720, category: "remotes", image: "images/UFO-R11.jpg" },
    { id: 98, name: "UFO-R2-RF", description: "Smart WiFi RF+IR Universal Remote Controller Blaster Appliances. Power Input: DC 5V/1A (Micro usb2.0), Controlling Distance: Horizontal direction ≤8m, RF: 433/315MHz", price: 1720, category: "remotes", image: "images/UFO-R2-RF.jpg" },
    { id: 99, name: "UFO-R6", description: "WiFi Infrared Remote Control Smart Home Blaster Wireless Control via APP. Power Input:5V DC 1A (Micro USB), IR Distance:≤8m", price: 1320, category: "remotes", image: "images/UFO-R6.jpg" },
    { id: 100, name: "WR-FL-S16-BK", description: "MOES Tuya WiFi Smart IR Thermostat AC Remote Controller Temperature and Humidity Sensor Supports Offline AC Control. Input: DC 5V/1A, Infrared Range: ≤ 10 Meters", price: 3350, category: "remotes", image: "images/WR-FL-S16-BK.jpg" },
    { id: 101, name: "WR-TY-THR", description: "Wi-Fi Smart IR Remote Control with Temperature and Humidity Sensor for Air Conditioner TV AC", price: 2100, category: "remotes", image: "images/WR-TY-THR.jpg" },

    // ===== TOUCH SCREENS =====
    { id: 102, name: "Touch screen 12inch", description: "12 inch Zigbee Multifunction Touch Screen Wall Switch, Smart Home Control Panel, Music Host, Tuya, WiFi, 12\" with Dimmer and Background Music Player, Smart Life Tuya App Control Timer Switch for Smart Appliances, Support Video Doorbell Two-Way Intercom, built in 100watt amplifier and speaker", price: 36000, category: "touch-screens", image: "images/Touch screen 12inch.jpg" },
    { id: 103, name: "CCP-TY10", description: "Smart 10'' Multi-control Touch Screen Panel with built-in alexa. 10〃，EU/US type; Alexa build-in, 1 One Touch to Control Smart Devices, 2 Actual relay button, 3 10-inch HD LCD Screen for Clearly Display, 4 ZigBee+Bluetooth Gateway include", price: 30000, category: "touch-screens", image: "images/CCP-TY10.jpg" },
    { id: 104, name: "CCP-S02-UN", description: "Smart Multi-control 8\" Touch Screen Panel. 1 Alexa Built-in, 2 One Touch to Control Smart Devices, 3 One Touch To Trigger Smart Scenes, 4 8-inch HD LCD Screen for Clearly Display, 5 ZigBee Gateway+Ble mesh include, 6 Built-In IR Control, 7 Built in 50W Amplifier Works with spotify only", price: 23500, category: "touch-screens", image: "images/CCP-S02-UN.jpg" },
    { id: 105, name: "CCP-US-AVS", description: "Smart US Multi-control Touch Screen Panel. 1 Alexa Built-in, 2 One Touch to Control Smart Devices, 3 One Touch To Trigger Smart Scenes, 4 5-inch HD LCD Screen for Clearly Display, 5 ZigBee Gateway include", price: 16500, category: "touch-screens", image: "images/CCP-US-AVS.jpg" },
    { id: 106, name: "CCP-TY-EU-LN", description: "Smart 4'' Multi-control Touch Screen Panel. 1 Alexa Built-in, 2 One Touch to Control Smart Devices, 3 Linux system, 4 4-inch HD LCD Screen for Clearly Display, 5 ZigBee Gateway include", price: 13280, category: "touch-screens", image: "images/CCP-TY-EU-LN.jpg" },
    { id: 107, name: "CCP-HT-GAC", description: "Smart Thermostat Control Panel. 1 zigbee Thermostat for water or gas Boiler, 2 Built In Temperature Sensor, 3 One Touch to Control Smart Devices, 4 One Touch To Trigger Smart Scenes, 5 Brightness Control, 6 ZigBee Gateway include", price: 17270, category: "touch-screens", image: "images/CCP-HT-GAC.jpg" },
    { id: 108, name: "CCP-S03-EU", description: "Smart Knob Central Control Screen. 1 Ultra-smooth knob & Touchscreen, 2 3-channel Relay & Customizable Switches, 3 Built-in Pomodoro Timer, 4 Device&Scene Integration", price: 11020, category: "touch-screens", image: "images/CCP-S03-EU.jpg" },
    { id: 109, name: "CCP-S01-EU", description: "Smart 3.5\" Multi-control Touch Screen Panel. 1 One Touch to Control Smart Devices, 2 One Touch To Trigger Smart Scenes, 3 3.5-inch HD LCD Screen for Clearly Display, 4 Built In IR Control+Bluetooth MESH HUB", price: 8600, category: "touch-screens", image: "images/CCP-S01-EU.jpg" },
    { id: 110, name: "Handheld Control Panel", description: "Smart WiFi IR Handheld center Control Panel. 1 One Touch to Control Smart Devices, 2 One Touch To Trigger Smart Scenes, 3 Wireless Design with Charging Dock&Cable, 4 Infrared Control as a remote controller, 5 lithium battery", price: 9830, category: "touch-screens", image: "images/Handheld Control Panel.jpg" },

    // ===== WIFI SAFETY AND SECURITY SENSORS =====
    { id: 111, name: "WSS-S-GL", description: "WiFi Gas Sensor. AC100-250v US/EU adapter include", price: 2300, category: "wifi-security", image: "images/WSS-S-GL.jpg" },
    { id: 112, name: "WSS-JM-WL-A", description: "WiFi Water leakage detector. 2*AAA battery", price: 1250, category: "wifi-security", image: "images/WSS-JM-WL-A.jpg" },
    { id: 113, name: "WV-QY-WH", description: "WiFi Smart Water Gas Valve Controller Pipeline Auto Shut OFF. EU adapter, Valve pressure:.6MPa Torque:30-60kg.cm Closing time: 5-10s Opening time:5-10s, Valve specifications: 1 inch, 1.25 inch.", price: 3020, category: "wifi-security", image: "images/WV-QY-WH.jpg" },
    { id: 114, name: "WSS-S-SSD-A", description: "WiFi Smoke detectors. 2*AAA battery", price: 2310, category: "wifi-security", image: "images/WSS-S-SSD-A.jpg" },
    { id: 115, name: "WSS-FL-GWM-A", description: "WiFi Gate magnetic sensor. 2*AAA battery", price: 1240, category: "wifi-security", image: "images/WSS-FL-GWM-A.jpg" },
    { id: 116, name: "WSS-FL-TH-A", description: "WiFi Temperature and humidity probe. 2*AAA battery", price: 1060, category: "wifi-security", image: "images/WSS-FL-TH-A.jpg" },
    { id: 117, name: "WSS-LO-SLA-U", description: "WiFi Siren audible and visual alarm. USB 5V1A", price: 1840, category: "wifi-security", image: "images/WSS-LO-SLA-U.jpg" },

    // ===== ZIGBEE SAFETY AND SECURITY SENSORS =====
    { id: 118, name: "ZSS-QY-GL", description: "ZigBee Smart Gas Leakage Detector Combustible Sensor. Power : USB-C", price: 2420, category: "zigbee-security", image: "images/ZSS-QY-GL.jpg" },
    { id: 119, name: "ZSS-QY-WL-C", description: "Zigbee Water leakage detector. 1*CR2032 battery", price: 1400, category: "zigbee-security", image: "images/ZSS-QY-WL-C.jpg" },
    { id: 120, name: "ZV-QY-WH", description: "Zigbee Smart Water Gas Valve Controller Pipeline Auto Shut OFF. EU adapter, Valve pressure:.6MPa Torque:30-60kg.cm Closing time: 5-10s Opening time:5-10s, Valve specifications: 1 inch, 1.25 inch.", price: 3400, category: "zigbee-security", image: "images/ZV-QY-WH.jpg" },
    { id: 121, name: "ZSS-HM-SSD01-A", description: "Zigbee Smoke detectors. 1*CR123A battery", price: 2820, category: "zigbee-security", image: "images/ZSS-HM-SSD01-A.jpg" },
    { id: 122, name: "ZSS-S01-GWM-C", description: "Zigbee Gate magnetic sensor. 1*CR2032 Battery", price: 1330, category: "zigbee-security", image: "images/ZSS-S01-GWM-C.jpg" },
    { id: 123, name: "ZSS-Z-VBR", description: "Zigbee Vibration Sensor. 2*AAA Battery", price: 1600, category: "zigbee-security", image: "images/ZSS-Z-VBR.jpg" },
    { id: 124, name: "ZSS-KB-TH-LF-C", description: "Zigbee Temperature and humidity probe. 1*CR2032 Battery", price: 1640, category: "zigbee-security", image: "images/ZSS-KB-TH-LF-C.jpg" },
    { id: 125, name: "ZSS-S01-TH", description: "Zigbee Temperature and humidity probe. 1*CR2032 Battery", price: 1220, category: "zigbee-security", image: "images/ZSS-S01-TH.jpg" },
    { id: 126, name: "ZSS-LO-SLA-U", description: "Zigbee Siren audible and visual alarm. USB 5V 1A", price: 1580, category: "zigbee-security", image: "images/ZSS-LO-SLA-U.jpg" },
    { id: 127, name: "ZSS-Z-SOS-C", description: "Zigbee SOS button. 1*CR2032 battery", price: 1170, category: "zigbee-security", image: "images/ZSS-Z-SOS-C.jpg" },
    { id: 128, name: "ZSS-HM-CO-A", description: "Zigbee CO detectors. 2*AA battery", price: 3370, category: "zigbee-security", image: "images/ZSS-HM-CO-A.jpg" },
    { id: 129, name: "ZSS-LM01", description: "ZigBee Ultrasonic Liquid Level Sensor. EU Adapter", price: 4970, category: "zigbee-security", image: "images/ZSS-LM01.jpg" },

    // ===== ZIGBEE & BLUETOOTH HUBS =====
    { id: 130, name: "BHUB-W", description: "Bluetooth Wireless HUB. USB 5V 1A", price: 1110, category: "hubs", image: "images/BHUB-W.jpg" },
    { id: 131, name: "BHUB", description: "Bluetooth Wired HUB. USB 5V 1A", price: 5440, category: "hubs", image: "images/BHUB.jpg" },
    { id: 132, name: "ZHUB-W", description: "Tuya ZigBee Smart Gateway Wireless Hub Smart Home Automation for All Tuya ZigBee3.0 Smart Products. Total Number Connected : 35 Devices, Adapter Output: 5V 2A", price: 2460, category: "hubs", image: "images/ZHUB-W.jpg" },
    { id: 133, name: "MZHUB", description: "Tuya Zigbee Matter Thread Gateway Smart Home Bridge Matter Hub. Dimensions: 90mm×90mm×22mm, Power input: 5V 1A, Power interface: Type C, Wireless protocol: Zigbee, Thread, Total Number Connected : 80 Devices", price: 4850, category: "hubs", image: "images/MZHUB.jpg" },
    { id: 134, name: "ZHUB", description: "Tuya ZigBee Smart Gateway Wired Hub Smart Home Automation for All Tuya ZigBee3.0 Smart Products. Total Number Connected : 80 Devices, Adapter Output: 5V 2A", price: 3870, category: "hubs", image: "images/ZHUB.jpg" },
    { id: 135, name: "MHUB", description: "Multi-Mode Smart Home Gateway ZigBee WiFi BLE Mesh Wired Hub. Electrical parameters: 5V 2A, Total Number Connected : 80 Devices", price: 5890, category: "hubs", image: "images/MHUB.jpg" },
    { id: 136, name: "ZZJ-R02", description: "MOES ZigBee Signal Repeater Amplifier USB Extender for Tuya Smart ZigBee Devices, Power Input: 5V=1A", price: 1430, category: "hubs", image: "images/ZZJ-R02.jpg" },

    // ===== GARAGE OPENERS =====
    { id: 137, name: "WM-102-M", description: "Wi-Fi mini smart Garage Door Opener Remote switch. mobile App control, voice control, warning message", price: 1970, category: "garage", image: "images/WM-102-M.jpg" },
    { id: 138, name: "ZM-102-M", description: "Zigbee mini smart Garage Door Opener Remote switch. mobile App control, voice control, warning message", price: 2160, category: "garage", image: "images/ZM-102-M.jpg" },
    { id: 139, name: "MS-102", description: "Wi-Fi smart Garage Door Opener Remote switch. mobile App control, voice control, warning message, Voltage：100-240V AC 50/60HZ", price: 2430, category: "garage", image: "images/MS-102.jpg" },
    { id: 140, name: "WM-JM-102-US", description: "Wi-Fi smart Garage Door Opener Remote switch. mobile App control, voice control, warning message, 5V 1A", price: 3110, category: "garage", image: "images/WM-JM-102-US.jpg" },
    { id: 141, name: "4 CH DIY Smart Switch", description: "4 CH Tuya Smart Switch WiFi DIY Timer 7-32V 4CH RF Voice Control Smart Home Automation Module Works with Alexa Google Home, Compatible Amazon Alexa", price: 2700, category: "garage", image: "images/4 CH DIY Smart Switch.jpg" },

    // ===== ALEXA DEVICES =====
    { id: 142, name: "Alexa Echo Frames", description: "Echo Frames (2nd Gen) | Smart audio sunglasses with Alexa | Classic Black with new polarized blue mirror sunglass lenses", price: 30000, category: "alexa", image: "images/Alexa Echo Frames.jpg" },
    { id: 143, name: "Echo Show 15", description: "Echo Show 15 | With a 15.6” Full HD (1080p) smart display with Alexa and Fire TV built in, with built-in mic and 5mp camera", price: 30000, category: "alexa", image: "images/Echo Show 15.jpg" },
    { id: 144, name: "Alexa Voice assistant", description: "Alexa pir can control compatible smart home devices like security cameras, lights, thermostats, and more. Camera: 13MP for Video call friends and family or take a picture. 10.1\" HD screen that’s designed to move with you. Take a look around when you’re away - Securely access the built-in camera to remotely monitor your home anytime", price: 29000, category: "alexa", image: "images/Alexa Voice assistant.jpg" },
    { id: 145, name: "Echo Show 8", description: "Amazon Echo Show 8 3rd Gen can show you even more - 8” HD touchscreen, adaptive color, and stereo speakers bring entertainment to life. Make video calls with a 13 MP camera that uses auto-framing to keep you centered", price: 14500, category: "alexa", image: "images/Echo Show 8.jpg" },
    { id: 146, name: "Smart echo show 5", description: "Amazon Echo Show 5 3rd Gen Voice control smart home devices Display: 5.5\" touch screen, Camera: 2 MP camera, Audio: Full range 1.65\" built-in speaker. SMALL SIZE, BIGGER SOUND – Stream your favorite music, shows, podcasts, and more. Includes a 5.5\" display so you can view shows, song titles, and more at a glance", price: 7700, category: "alexa", image: "images/Smart echo show 5.jpg" },
    { id: 147, name: "alexa echo dot 5", description: "Amazon Alexa Eco Dot 5th Generation", price: 5800, category: "alexa", image: "images/alexa echo dot 5.jpg" },
    { id: 148, name: "alexa Echo Kids Dot", description: "Echo Kids Dot (5th Gen 2022) with Fire Dragon New Sealed. 1.73\" front-firing speaker. Kids can ask Alexa to play music, read a bedtime story, get help with their homework, and more. You can also set daily time limits and review activity in the Amazon Parent Dashboard.", price: 5800, category: "alexa", image: "images/alexa Echo Kids Dot.jpg" },
    { id: 149, name: "Echo Pop", description: "Amazon Echo Pop | Full sound compact smart speaker with Alexa CONTROL MUSIC WITH YOUR VOICE – Ask Alexa to play music, audiobooks, and podcasts. MAKE ANY SPACE A SMART SPACE – Easily control smart home devices LIGHT BAR – Alexa doesn’t begin listening until your device hears you say “Alexa” and the light bar turns blue.", price: 3470, category: "alexa", image: "images/Echo Pop.jpg" },
    { id: 150, name: "Echo Spot", description: "All-new Amazon Echo Spot (2024 release), Smart alarm clock with vibrant sound + Alexa, Black", price: 5600, category: "alexa", image: "images/Echo Spot.jpg" }
];