(() => {
  'use strict';
  const app = document.getElementById('smart-home-app');
  if (!app) return;
  const lang = document.documentElement.lang === 'en' ? 'en' : 'ar';
  const base = location.pathname.replace(/[^/]*$/, '');
  const API = (p) => base + p.replace(/^\//,'');
  const t = {
    ar:{steps:['البيانات','المتطلبات','المخطط','التحليل','المراجعة'],name:'الاسم الكامل *',email:'البريد الإلكتروني *',phone:'رقم الهاتف *',type:'نوع المشروع',area:'المساحة م²',floors:'عدد الأدوار',location:'الموقع',requirements:'اختر الأنظمة المطلوبة',plan:'رفع المخطط',planHint:'JPG / PNG / PDF / DXF / DWG — حتى 10MB لكل ملف',drop:'اسحب الملفات هنا أو اضغط للاختيار',analyze:'تحليل المخطط',next:'التالي',back:'السابق',result:'النتائج',review:'المراجعة الهندسية',send:'إرسال طلب التصميم النهائي',notes:'ملاحظات إضافية',error:'حدث خطأ. حاول مرة أخرى.',required:'يرجى استكمال الاسم والبريد والهاتف.',ai:'جاري تحليل المخطط بالذكاء الاصطناعي...',openViewer:'فتح المعاينة التفاعلية',saved:'تم إنشاء المعاينة الخاصة بمشروعك.'},
    en:{steps:['Project','Requirements','Plan','Analysis','Review'],name:'Full Name *',email:'Email *',phone:'Phone *',type:'Project Type',area:'Area m²',floors:'Floors',location:'Location',requirements:'Select required systems',plan:'Upload Floor Plan',planHint:'JPG / PNG / PDF / DXF / DWG — up to 10MB per file',drop:'Drag files here or click to choose',analyze:'Analyze Plan',next:'Next',back:'Back',result:'Results',review:'Engineering Review',send:'Request Final Design',notes:'Additional notes',error:'Something went wrong. Please try again.',required:'Please complete name, email and phone.',ai:'Analyzing your floor plan with AI...',openViewer:'Open Interactive Preview',saved:'Your private project preview has been created.'}
  }[lang];
  const reqs = [['lighting','Lighting'],['curtains','Curtains'],['hvac','HVAC'],['security','Security'],['cctv','CCTV'],['access_control','Access Control'],['door_sensors','Door Sensors'],['window_sensors','Window Sensors'],['motion_sensors','Motion / Presence'],['temperature_sensors','Temperature Sensors'],['gas_sensors','Gas Sensors'],['water_leak','Water Leak'],['voice_control','Voice Control'],['mobile_control','Mobile App'],['central_panel','Central Panel'],['networking','Networking'],['scenes','Scenes'],['home_assistant','Home Assistant']];
  const state={step:0,data:{requirements:[]},files:[],result:null,error:''};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const apiJSON=async(url,opt={})=>{const r=await fetch(API(url),{credentials:'same-origin',...opt});let j=null;try{j=await r.json()}catch(_){throw new Error('Invalid server response')};if(!r.ok||j.success===false)throw new Error(j.message||t.error);return j};
  async function csrf(){return (await apiJSON('api/csrf-token.php')).csrf_token;}
  function progress(){return `<div class="smart-home-progress">${t.steps.map((x,i)=>`<div class="step ${i===state.step?'active':i<state.step?'done':''}">${i+1}. ${x}</div>`).join('')}</div>`;}
  function actions(back=true,label=t.next){return `<div class="smart-actions">${back?`<button type="button" class="smart-btn secondary" id="backBtn">${t.back}</button>`:'<span></span>'}<button type="button" class="smart-btn primary" id="nextBtn">${label}</button></div>`;}
  function render(){let c='';if(state.step===0)c=project();if(state.step===1)c=requirements();if(state.step===2)c=upload();if(state.step===3)c=loading();if(state.step===4)c=results();app.innerHTML=`<div class="smart-home-shell">${progress()}<section class="smart-card">${state.error?`<div class="smart-error">${esc(state.error)}</div>`:''}${c}</section></div>`;bind();}
  function project(){let d=state.data;return `<h2>${t.steps[0]}</h2><p class="smart-muted">${lang==='ar'?'بيانات المشروع هي الأساس للنموذج الرقمي الموحد.':'Project data becomes the basis of the unified digital model.'}</p><div class="smart-grid"><div class="smart-field"><label>${t.name}</label><input id="name" value="${esc(d.name)}" autocomplete="name"></div><div class="smart-field"><label>${t.email}</label><input id="email" type="email" value="${esc(d.email)}" autocomplete="email"></div><div class="smart-field"><label>${t.phone}</label><input id="phone" value="${esc(d.phone)}" autocomplete="tel"></div><div class="smart-field"><label>${t.type}</label><select id="project_type"><option value="villa">${lang==='ar'?'فيلا':'Villa'}</option><option value="apartment">${lang==='ar'?'شقة':'Apartment'}</option><option value="office">${lang==='ar'?'مكتب':'Office'}</option><option value="commercial">${lang==='ar'?'تجاري':'Commercial'}</option><option value="other">${lang==='ar'?'أخرى':'Other'}</option></select></div><div class="smart-field"><label>${t.area}</label><input id="area" type="number" min="1" max="100000" value="${esc(d.area)}"></div><div class="smart-field"><label>${t.floors}</label><input id="floors" type="number" min="1" max="100" value="${esc(d.floors)}"></div><div class="smart-field full"><label>${t.location}</label><input id="location" value="${esc(d.location)}"></div></div>${actions(false)}`;}
  function requirements(){return `<h2>${t.requirements}</h2><p class="smart-muted">These selections add optional systems. ESSO core room rules will be applied automatically. AI analysis instructions are managed by ESSO server configuration files.</p><div class="smart-checks">${reqs.map(([k,label])=>`<label class="smart-check"><input type="checkbox" value="${k}" ${state.data.requirements.includes(k)?'checked':''}> ${label}</label>`).join('')}</div>${actions(true)}`;}

  function upload(){return `<h2>${t.plan}</h2><p class="smart-muted">${t.planHint}</p><div class="smart-upload" id="drop"><i class="fas fa-cloud-upload-alt"></i><div>${t.drop}</div><input id="fileInput" type="file" accept=".jpg,.jpeg,.png,.pdf,.dxf,.dwg" multiple hidden></div><div class="smart-files">${state.files.map((f,i)=>`<div class="smart-file"><span>${esc(f.name)} (${Math.round(f.size/1024)} KB)</span><button type="button" class="smart-btn secondary remove" data-i="${i}">×</button></div>`).join('')}</div>${actions(true,t.analyze)}`;}
  function loading(){return `<h2>${t.ai}</h2><div class="smart-loader"><span class="smart-spinner"></span><strong>${t.ai}</strong></div><div class="smart-stage-list"><div class="smart-stage active">1. ${lang==='ar'?'رفع الملفات':'Upload files'}</div><div class="smart-stage">2. ${lang==='ar'?'تحليل المخطط':'Analyze floor plan'}</div><div class="smart-stage">3. ${lang==='ar'?'قواعد ESSO الهندسية':'ESSO engineering rules'}</div><div class="smart-stage">4. ${lang==='ar'?'بناء النموذج الرقمي':'Build digital model'}</div><div class="smart-stage">5. ${lang==='ar'?'تجهيز BOQ والمعاينة':'Prepare BOQ and preview'}</div></div>`;}
  function results(){const r=state.result||{};const a=r.analysis||{}, floors=a.floors||[], rec=r.recommendations||[], boq=r.boq||[], reviews=r.review_required||[], token=r.project_token||'';const rooms=floors.reduce((n,f)=>n+(f.rooms||[]).length,0);return `<h2>${t.result}</h2><div class="smart-summary"><div class="smart-stat"><span>${t.area}</span><strong>${a.project?.total_area_sqm??state.data.area??'TBD'}</strong></div><div class="smart-stat"><span>${t.floors}</span><strong>${floors.length}</strong></div><div class="smart-stat"><span>${lang==='ar'?'الغرف':'Rooms'}</span><strong>${rooms}</strong></div><div class="smart-stat"><span>${t.review}</span><strong>${reviews.length}</strong></div></div><h3>${lang==='ar'?'تفاصيل الغرف':'Room Breakdown'}</h3><div class="smart-table-wrap"><table class="smart-table"><thead><tr><th>${lang==='ar'?'الغرفة':'Room'}</th><th>${t.area}</th><th>Doors</th><th>Windows</th><th>Confidence</th></tr></thead><tbody>${floors.flatMap(f=>(f.rooms||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${x.area_sqm??'TBD'}</td><td>${x.doors||0}</td><td>${x.windows||0}</td><td>${Math.round(x.confidence||0)}%</td></tr>`)).join('')}</tbody></table></div><h3 style="margin-top:24px">${lang==='ar'?'الأجهزة المقترحة':'Device Plan'}</h3><div class="smart-table-wrap"><table class="smart-table"><thead><tr><th>${lang==='ar'?'الجهاز':'Device'}</th><th>${lang==='ar'?'المكان':'Room'}</th><th>${lang==='ar'?'الكمية':'Qty'}</th><th>Confidence</th></tr></thead><tbody>${rec.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.room)}</td><td>${x.qty}</td><td>${Math.round(x.confidence||0)}%</td></tr>`).join('')||'<tr><td colspan="4">TBD</td></tr>'}</tbody></table></div><h3 style="margin-top:24px">${lang==='ar'?'BOQ مبدئي':'Preliminary BOQ'}</h3><div class="smart-table-wrap"><table class="smart-table"><thead><tr><th>${lang==='ar'?'البند':'Item'}</th><th>${lang==='ar'?'الكمية':'Qty'}</th><th>${lang==='ar'?'السعر':'Price'}</th></tr></thead><tbody>${boq.map(x=>`<tr><td>${esc(x.item)}</td><td>${x.quantity}</td><td>TBD</td></tr>`).join('')||'<tr><td colspan="3">TBD</td></tr>'}</tbody></table></div>${reviews.length?`<div class="smart-info smart-review"><strong>${t.review}</strong><ul>${reviews.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${token?`<div class="smart-info">${esc(t.saved)}</div><div class="smart-actions"><a class="smart-btn secondary" href="project-viewer.html?token=${encodeURIComponent(token)}">${t.openViewer}</a><button type="button" class="smart-btn accent" id="submitBtn">${t.send}</button></div><div class="smart-field"><label>${t.notes}</label><textarea id="requestNotes"></textarea></div>`:actions(true)}`;}
  function bind(){document.getElementById('backBtn')?.addEventListener('click',()=>{state.error='';state.step=Math.max(0,state.step-1);render()});document.getElementById('nextBtn')?.addEventListener('click',()=>{state.error='';if(state.step===0){state.data.name=document.getElementById('name').value.trim();state.data.email=document.getElementById('email').value.trim();state.data.phone=document.getElementById('phone').value.trim();state.data.project_type=document.getElementById('project_type').value;state.data.area=document.getElementById('area').value;state.data.floors=document.getElementById('floors').value;state.data.location=document.getElementById('location').value.trim();if(!state.data.name||!state.data.email||!state.data.phone){state.error=t.required;render();return}state.step=1;render()}else if(state.step===1){state.data.requirements=[...document.querySelectorAll('.smart-check input:checked')].map(x=>x.value);state.step=2;render()}else if(state.step===2)runAnalysis()});document.querySelectorAll('.remove').forEach(b=>b.addEventListener('click',()=>{state.files.splice(+b.dataset.i,1);render()}));document.getElementById('submitBtn')?.addEventListener('click',submitRequest);document.getElementById('editAiBtn')?.addEventListener('click',()=>{state.step=1;render()});const drop=document.getElementById('drop'), input=document.getElementById('fileInput');if(drop&&input){drop.addEventListener('click',()=>input.click());drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');state.files=[...e.dataTransfer.files].filter(f=>f.size<=10*1024*1024);render()});input.addEventListener('change',()=>{state.files=[...input.files].filter(f=>f.size<=10*1024*1024);render()})}}
  async function runAnalysis(){if(!state.files.length){state.error=lang==='ar'?'اختر ملفًا واحدًا على الأقل.':'Select at least one file.';render();return}state.error='';state.step=3;render();try{const token=await csrf();const fd=new FormData();state.files.forEach(f=>fd.append('files[]',f));fd.append('csrf_token',token);const up=await apiJSON('api/upload.php',{method:'POST',body:fd});const an=await apiJSON('api/analyze.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:token,files:up.files.map(x=>x.id),requirements:state.data.requirements,project:state.data})});const saved=await apiJSON('api/project.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:token,project:state.data,analysis:an.analysis,recommendations:an.recommendations,boq:an.boq,review_required:an.review_required,files:up.files})});state.result={...an,...saved};state.step=4;render()}catch(e){state.error=e.message||t.error;state.step=2;render()}}
  async function submitRequest(){try{const token=await csrf();const notes=document.getElementById('requestNotes')?.value?.trim()||'';await apiJSON('api/final-request.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:token,project_token:state.result.project_token,notes})});state.error='';app.innerHTML=`<div class="smart-home-shell"><section class="smart-card"><div class="smart-info"><h2>${lang==='ar'?'تم إرسال طلبك بنجاح':'Request submitted successfully'}</h2><p>${lang==='ar'?'سيراجع فريق ESSO المشروع ويتواصل معك بالخطوات التالية.':'The ESSO team will review the project and contact you with the next steps.'}</p></div></section></div>`}catch(e){state.error=e.message||t.error;render()}}
  render();
})();
